//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Celebration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Celebration.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is celebrating {1} with team..
        /// </summary>
        internal static string EventCardTitle {
            get {
                return ResourceManager.GetString("EventCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has already been deleted..
        /// </summary>
        internal static string EventNotExistMessage {
            get {
                return ResourceManager.GetString("EventNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has already been passed..
        /// </summary>
        internal static string EventPassedMessage {
            get {
                return ResourceManager.GetString("EventPassedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you joined a new team. Would you like to share your events in {0} as well?.
        /// </summary>
        internal static string EventShareMessage {
            get {
                return ResourceManager.GetString("EventShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0}, This event is skipped for current year and won&apos;t be shared with team..
        /// </summary>
        internal static string EventSkippedMessage {
            get {
                return ResourceManager.GetString("EventSkippedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is celebrating {1} with team..
        /// </summary>
        internal static string PreviewHeader {
            get {
                return ResourceManager.GetString("PreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, you have an upcoming event in next 3 days. If you take no action i will post this celebration..
        /// </summary>
        internal static string PreviewText {
            get {
                return ResourceManager.GetString("PreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey I am Celebration bot.Thanks for installing me..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Celebration bot. {0} installed me in {1}. I’m here to help everyone celebrate birthdays, anniversaries, and anything else you tell me about..
        /// </summary>
        internal static string WelcomeMessageForTeam {
            get {
                return ResourceManager.GetString("WelcomeMessageForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for installing me. I’m ready to help you celebrate special events with your team. Currently you don’t have me in any of your teams.
        /// </summary>
        internal static string WelcomeMessagePart1 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click get started to start adding your own events..
        /// </summary>
        internal static string WelcomeMessagePart2 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then install me in a team so that I can help you and your team members remember and share their events..
        /// </summary>
        internal static string WelcomeMessagePart3 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m ready to help you celebrate special events with your team. Click get started to add your own events..
        /// </summary>
        internal static string WelcomeMessagePart4 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart4", resourceCulture);
            }
        }
    }
}
